In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [38]:
data= pd.read_csv('./data/Training Data.csv')
target= pd.read_csv('./data/Training Data Target.csv')
test_data= pd.read_csv('./data/Test Data.csv')
sample= pd.read_csv('./data/Sample Submission.csv')

In [50]:
data.head(2)

user_id      aov category
0    37327  29128.0   Phones
1    37327    354.0  Fashion

In [51]:
target.tail(2)

user_id   aov category
13243    49900 -9999  Fitness
13244    49912 -9999  Fashion

In [52]:
test_data.head(2)

Unnamed: 0  user_id      aov category
0           0    43323  19115.0   Phones
1           1    43323  29309.0   Phones

In [53]:
sample.head(2)

user_id                                pred3
0    43323  Laptops, Fashion, Consumer Durables
1     4269  Laptops, Fashion, Consumer Durables

In [89]:
sample_ids = sample['user_id']
np.sort(sample_ids)[:15]

array([ 2,  3,  8, 10, 13, 15, 17, 18, 20, 22, 23, 24, 31, 32, 36],
      dtype=int64)

In [83]:
train_ids = data['user_id']
np.sort(train_ids)[:15]

array([1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4], dtype=int64)

In [84]:
target_ids = target['user_id']
np.sort(target_ids)[:5]

array([ 1,  6, 14, 16, 19], dtype=int64)

In [90]:
test_ids = test_data['user_id']
np.sort(test_ids)[:15]

array([2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 8], dtype=int64)

In [61]:
train_ids.shape, target_ids.shape, test_ids.shape, sample_ids.shape

((29972,), (13245,), (19981,), (19981,))

In [91]:
train_ids.shape, target_ids.shape, test_ids.shape, sample_ids.shape

((257407,), (13245,), (172554,), (19981,))

In [75]:
for ti in test_ids:
    if ti in train_ids:
        print(ti)

In [78]:
# train = 1,1,1,2,2,2,2,3,3,3,4,4,5,5,5,6,6
# target= 1,    2,      3                        # train label 1 prediction for each id
# test =              7,7,7,8,8,8,9,10,10
# sample=             7,    8,    9,10           # test label 3 prediction but all in same row

In [80]:
target.value_counts('user_id')

user_id
1        1
33507    1
33467    1
33469    1
33474    1
        ..
16502    1
16505    1
16510    1
16511    1
50079    1
Length: 13245, dtype: int64

In [81]:
target.groupby('user_id').count()

aov  category
user_id               
1          1         1
6          1         1
14         1         1
16         1         1
19         1         1
...      ...       ...
49999      1         1
50030      1         1
50066      1         1
50075      1         1
50079      1         1

[13245 rows x 2 columns]